spring:
  application:
    name: product-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  h2:
    console:
      enabled: true
      path: /h2/console
  datasource:
    url: jdbc:h2:file:~/products
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8091
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://localhost:8761/eureka}

